version: "3.9"  

services:
  web:
    build: .
    command: gunicorn nasa_application.wsgi:application -b 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./nasa_application/db.sqlite3:/app/db.sqlite3
