services:
  - name: nasa-application
    type: web
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      cd nasa_application/nasa_application
      gunicorn wsgi:application
