services:
  - type: web
    name: nasa-application
    root_directory: /nasa_application
    build_command: |
      pip install -r requirements.txt &&
      python manage.py migrate
    start_command: daphne nasa_application.asgi:application --bind 0.0.0.0:$PORT
    env: production
    secrets:
      - name: SECRET_KEY
        value: ${SECRET_KEY}
