services:
  - type: web
    name: nasa-application
    root_directory: /nasa_application 
    build_command: |
      pip install -r requirements.txt &&
    start_command: gunicorn nasa_application.nasa_application.wsgi:application --bind 0.0.0.0:$PORT
    env: production
    secrets:
      - name: SECRET_KEY
        value: ${SECRET_KEY}
