services:
  - type: web
    name: nasa-application
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn nasa_application.wsgi:application --bind 0.0.0.0:$PORT"
