services:
  - type: web
    name: nasa-application
    root_directory: /
    build_command: |
      pip install -r requirements.txt &&
      python manage.py migrate
    start_command: python manage.py runserver
    env: production
    secrets:
      - name: SECRET_KEY
        value: ${SECRET_KEY}
