# Generated by Django 5.1.3 on 2024-11-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asteroids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asteroide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_diameter', models.FloatField()),
                ('max_diameter', models.FloatField()),
                ('relative_velocity', models.FloatField()),
                ('miss_distance', models.FloatField()),
                ('absolute_magnitude', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Asteroid',
        ),
    ]
