# Generated by Django 5.1.2 on 2024-11-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asteroids', '0002_asteroide_delete_asteroid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroide',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
