openapi: 3.0.3
info:
  title: Asteroides API
  version: 1.0.0
  description: API para gerenciamento de asteroides
paths:
  /asteroids/:
    get:
      operationId: asteroids_retrieve
      tags:
      - asteroids
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /asteroids/{id}/:
    get:
      operationId: asteroids_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - asteroids
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: asteroids_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - asteroids
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: asteroids_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - asteroids
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /asteroids/create/:
    post:
      operationId: asteroids_create_create
      tags:
      - asteroids
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /asteroids/search/:
    get:
      operationId: asteroids_search_retrieve
      tags:
      - asteroids
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
